import { useCallback, useRef, useState } from "react";

/** Plays ElevenLabs speech generated by the backend (keys stay server-side). */
export function useVoice() {
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const [speaking, setSpeaking] = useState(false);
  const [voiceError, setVoiceError] = useState<string | null>(null);

  const stop = useCallback(() => {
    audioRef.current?.pause();
    audioRef.current = null;
    setSpeaking(false);
  }, []);

  const speak = useCallback(
    async (text: string) => {
      if (!text.trim()) return;
      stop();
      setVoiceError(null);
      try {
        const response = await fetch("/api/tts", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ text }),
        });
        if (!response.ok) {
          const detail = (await response.json().catch(() => ({}))) as { error?: string };
          throw new Error(detail.error ?? "Voice is unavailable right now.");
        }
        const url = URL.createObjectURL(await response.blob());
        const audio = new Audio(url);
        audioRef.current = audio;
        audio.onended = () => {
          setSpeaking(false);
          URL.revokeObjectURL(url);
        };
        setSpeaking(true);
        await audio.play();
      } catch (error) {
        setSpeaking(false);
        setVoiceError(error instanceof Error ? error.message : "Voice failed.");
      }
    },
    [stop],
  );

  return { speak, stop, speaking, voiceError };
}
